services:
  php:
    container_name: localisto-php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../backend:/var/www
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - localisto-network
    ports:
      - "6001:6001"
    entrypoint: >
      sh -c "
        chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
        php-fpm
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: localisto-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - localisto-network

  mysqldb:
    image: mysql:8.0
    container_name: localisto-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: localisto
      MYSQL_ROOT_PASSWORD: saberi
      MYSQL_USER: localisto_user
      MYSQL_PASSWORD: localpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - localisto-network
    healthcheck:
      # Use CMD-SHELL so the MYSQL_ROOT_PASSWORD environment variable is expanded inside the container.
      # Use $$ to escape the $ so Compose does not substitute it at config time; Compose will send a single $ to the container.
      test: ["CMD-SHELL", "mysqladmin --protocol=TCP ping -h localisto-mysql -u root -p\"$$MYSQL_ROOT_PASSWORD\" >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 90s

  redis:
    image: redis:7
    container_name: localisto-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - localisto-network

  apache:
    container_name: localisto-apache
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../backend:/var/www
      - ../frontend:/usr/local/apache2/htdocs/frontend
      - ./apache/localisto.conf:/usr/local/apache2/conf/extra/localisto.conf
    depends_on:
      php:
        condition: service_started
    networks:
      - localisto-network

#   nginx:
#     image: nginx:alpine
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ../backend:/var/www
#       - ../frontend:/usr/share/nginx/html/frontend
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       php:
#         condition: service_started
#     networks:
#       - laravel

volumes:
  mysql_data:
  redis_data:

networks:
  localisto-network:
