server {
    listen 80;
    index index.php;
    server_name admin.localisto.local api.localisto.local;

    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 80;
    server_name localisto.local;

    root /usr/share/nginx/html/frontend;  # your frontend folder in Docker
    index index.html;

    location / {
        try_files $uri @rewrite_slug;
    }

    location @rewrite_slug {
        # Strip the first directory component (store slug) and try again
        rewrite ^/[^/]+/(.*)$ /$1 last;
        
        # Fallback to index.html for SPA routing or if file not found
        rewrite ^ /index.html last;
    }
}
